language: node_js
node_js:
- '5.1'
script:
  - npm run build
deploy:
  provider: modulus
  api_key:
    secure: uM5UYAg7KC0Y1qv9y2zeS92eU44T7W7sRwJDdUtOMeAWrbxQr6QMO2lOnJTfqIBIg6uDF18TGAdoGbIciT0Ax6+I8OVGt+1lSZxdiDXGaKkDmIyXMcd42b4ehNg/4pX/zKyeKGGEv73rQo1dmThjhe2mRP8wqaeZJ4a366TWvPpy3T9JlJRpJclwYn8Ou37yTJqWsLJgg+DyvcHhKebpXuAHDakjGjmuxDElJsaEkcC3+qEVjfeHfjYPMgHS+NEmt9N3usVqlc60np5p1F3EgeBgyZn87Grg9h3maAG4Bj3bOVFX4KlMOqcTsw5etxC9xiCAg0hKl2ny6viIOc3d6k2Djxe3ieT6tvy8/QHUyg4vrKRkrbVOfx5eSp8hkpHPu0Ne3Dd1AVexCxyFj5K5EjdtiAZCHz7NxR5K9ZFGiW1ysl9f+VKEPbiU+R46zoSHMANFiyo0nhKjazFgxElVby3CE2I25Mz0yTP1c1mc5hM5TACiL3C1anFu321ESKW7CsQPesMuvSyH+TAS/TFvhG5C7k8dVeeEYD8OGpoBc418j9/4y/04nIR0VyK+pZTA4fo2lhQupLfG0U+SfGK5tByGekxpFl2234c1hlJL9RKwmHbuckRr1OGP4qNMGibvSri2kQoGmqYzkdovkqtxYhZW5QuMd+FCCMbzgHSIZb8=
  project_name: thisisyourpark-web
